repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: remove-tabs
        args: [ --whitespaces-count=4 ]

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
        language_version: python3.9

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9