sudo: required
dist: trusty

language: python

apt:
  packages:
    - python-dev

python: 3.6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python3-pip
  - sudo apt-get install python-virtualenv

install:
  - pip3 install codecov

script:
  - coverage run -m pytest

after_success:
  - codecov