os: linux
dist: xenial
language: python
python: 3.9

before_install:
  - sudo apt update
  - sudo apt install make python3-pip python-virtualenv

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - make coverage

after_success:
  - codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml