sudo: required
dist: xenial

language: python

apt:
  packages:
    - python-dev

python: 3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python3-pip
  - sudo apt-get install python-virtualenv

install:
  - pip3 install codecov codacy-coverage pytest-timeout

script:
  - coverage run -m pytest
  - coverage xml
  - coverage report

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml