os: linux
dist: xenial
language: python
python: 3.9

before_install:
  - apt update
  - apt install python3-pip python-virtualenv

install:
  - pip3 install codecov codacy-coverage pytest-timeout

script:
  - coverage run -m pytest
  - coverage xml
  - coverage report

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml