os: linux
dist: xenial
language: python
python: 3.9

before_install:
  - sudo apt update
  - sudo apt install python3-pip python-virtualenv

install:
  - pip3 install codecov pytest-timeout

script:
  - coverage run -m pytest
  - coverage xml
  - coverage report

after_success:
  - codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report