codecov:
  notify:
    require_ci_to_pass: no

coverage:
  range: "50...95"
  precision: 2
  round: down

  status:
    project:
      default:
        target: auto
        threshold: "0.05%"
    patch: false
    changes: false

  ignore:
    - '__init__.py'

comment: off