import pytest
from leetcode.p0049_group_anagrams import groupAnagrams, groupAnagrams2, groupAnagrams3


@pytest.mark.parametrize(
    ("strs", "expectation"),
    (
        (
            ["eat", "tea", "tan", "ate", "nat", "bat"],
            [["eat", "tea", "ate"], ["tan", "nat"], ["bat"]],
        ),
        (
            ["cab", "tin", "pew", "duh", "may", "ill", "buy", "bar", "max", "doc"],
            [
                ["doc"],
                ["bar"],
                ["buy"],
                ["ill"],
                ["may"],
                ["tin"],
                ["cab"],
                ["pew"],
                ["max"],
                ["duh"],
            ],
        ),
        (
            ["fly", "sit", "dog", "gee", "ivy", "bat", "jun"],
            [["jun"], ["ivy"], ["fly"], ["bat"], ["sit"], ["dog"], ["gee"]],
        ),
        (
            [
                "ron",
                "huh",
                "gay",
                "tow",
                "moe",
                "tie",
                "who",
                "ion",
                "rep",
                "bob",
                "gte",
                "lee",
                "jay",
                "may",
                "wyo",
                "bay",
                "woe",
                "lip",
                "tit",
                "apt",
                "doe",
                "hot",
                "dis",
                "fop",
                "low",
                "bop",
                "apt",
                "dun",
                "ben",
                "paw",
                "ere",
                "bad",
                "ill",
                "fla",
                "mop",
                "tut",
                "sol",
                "peg",
                "pop",
                "les",
            ],
            [
                ["pop"],
                ["peg"],
                ["fla"],
                ["ill"],
                ["bad"],
                ["tut"],
                ["ere"],
                ["paw"],
                ["sol"],
                ["dun"],
                ["bop"],
                ["low"],
                ["dis"],
                ["bob"],
                ["rep"],
                ["woe"],
                ["ion"],
                ["mop"],
                ["tie"],
                ["wyo"],
                ["tit"],
                ["les"],
                ["who"],
                ["apt", "apt"],
                ["fop"],
                ["hot"],
                ["ron"],
                ["gay"],
                ["gte"],
                ["moe"],
                ["lee"],
                ["huh"],
                ["lip"],
                ["jay"],
                ["tow"],
                ["may"],
                ["ben"],
                ["bay"],
                ["doe"],
            ],
        ),
    ),
)
def test_anagrams(strs, expectation):
    for res in groupAnagrams(strs):
        assert res in expectation

    for res in groupAnagrams2(strs):
        assert res in expectation

    for res in groupAnagrams3(strs):
        assert res in expectation
