name: flake8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkSyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Syntax Error Check
        run: |
          flake8 leetcode --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Coding Style Violations
        run: |
          flake8 leetcode --count --max-line-length=88 --ignore E203,E501,E741,W503 --show-source --statistics
          flake8 tests --count --max-line-length=88 --ignore E203,E501,E741,W503 --show-source --statistics